apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace: foo
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000