apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  type: NodePort
  selector:
    app: my-app-foo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000